feat(eslint-plugin): expose flatConfigs as property of default export
Currently, the flat configs object is only available as a named export
named `flatConfig`, which means that the usage example on #73873 (where
it's used as a property of the default export named `flatConfigs`)
doesn't work.

If you try to use `flatConfig` as a property of the default export, it
works but causes TypeScript errors if the consumer has type checking
enabled in their ESLint config:

```
eslint.config.mjs:180:24 - error TS2339: Property 'flatConfig' does not exist on type '{ rules: { 'google-font-display': RuleModule; 'google-font-preconnect': RuleModule; 'inline-script-id': RuleModule; 'next-script-for-ga': RuleModule; ... 16 more ...; 'no-unwanted-polyfillio': RuleModule; }; configs: { ...; }; }'.

180       eslintPluginNext.flatConfig.recommended,
                           ~~~~~~~~~~
```

This has caused quite a bit of confusion, as evidenced by activity on
https://github.com/vercel/next.js/discussions/49337 from after that PR
was merged. (I shared that confusion for a while!)

This PR attaches `flatConfig` to the default export as a property named
`flatConfigs`, while continuing to make it available as a named export
named `flatConfig` for backward compatibility. With this change, the
flat config is more easily usable like those of other popular ESLint
libraries:

```
// eslint.config.mjs
import js from "@eslint/js";
import reactPlugin from 'eslint-plugin-react';
import eslintPluginNext from '@next/eslint-plugin-next';

export default [
  ...js.configs.recommended,
  ...reactPlugin.configs.flat.recommended,
  ...eslintPluginImportX.flatConfigs.recommended,
]
```

I've also reorganized the code a bit, and added proper type checking
through `@eslint/types`.